package pokemonBattleSim.models;

import java.util.*;
import pokemonBattleSim.types.Attribute;
import pokemonBattleSim.types.Move;
import pokemonBattleSim.types.Type;

/*
 * Name, type, attribute, contest, PP, power, accuracy
 */

public class MoveList
{	public static Map < String, Move > moveMap = new HashMap<>();
	static
	{	
		moveMap.put("Pound", new Move("Pound", Type.NORMAL, Attribute.PHYSICAL, 35, 40, 100));
		moveMap.put("Karate Chop", new Move("Karate Chop", Type.FIGHTING, Attribute.PHYSICAL, 25, 50, 100));
		moveMap.put("Double Slap", new Move("Double Slap", Type.NORMAL, Attribute.PHYSICAL, 10, 15, 85));
		moveMap.put("Comet Punch", new Move("Comet Punch", Type.NORMAL, Attribute.PHYSICAL, 15, 18, 85));
		moveMap.put("Mega Punch", new Move("Mega Punch", Type.NORMAL, Attribute.PHYSICAL, 20, 80, 85));
		moveMap.put("Pay Day", new Move("Pay Day", Type.NORMAL, Attribute.PHYSICAL, 20, 40, 100));
		moveMap.put("Fire Punch", new Move("Fire Punch", Type.FIRE, Attribute.PHYSICAL, 15, 75, 100));
		moveMap.put("Ice Punch", new Move("Ice Punch", Type.ICE, Attribute.PHYSICAL, 15, 75, 100));
		moveMap.put("Thunder Punch", new Move("Thunder Punch", Type.ELECTRIC, Attribute.PHYSICAL, 15, 75, 100));
		moveMap.put("Scratch", new Move("Scratch", Type.NORMAL, Attribute.PHYSICAL, 35, 40, 100));
		moveMap.put("Vice Grip", new Move("Vice Grip", Type.NORMAL, Attribute.PHYSICAL, 30, 55, 100));
		moveMap.put("Guillotine", new Move("Guillotine", Type.NORMAL, Attribute.PHYSICAL, 5, -1, -1));
		moveMap.put("Razor Wind", new Move("Razor Wind", Type.NORMAL, Attribute.SPECIAL, 10, 80, 100));
		moveMap.put("Swords Dance", new Move("Swords Dance", Type.NORMAL, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Cut", new Move("Cut", Type.NORMAL, Attribute.PHYSICAL, 30, 50, 95));
		moveMap.put("Gust", new Move("Gust", Type.FLYING, Attribute.SPECIAL, 35, 40, 100));
		moveMap.put("Wing Attack", new Move("Wing Attack", Type.FLYING, Attribute.PHYSICAL, 35, 60, 100));
		moveMap.put("Whirlwind", new Move("Whirlwind", Type.NORMAL, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Fly", new Move("Fly", Type.FLYING, Attribute.PHYSICAL, 15, 90, 95));
		moveMap.put("Bind", new Move("Bind", Type.NORMAL, Attribute.PHYSICAL, 20, 15, 85));
		moveMap.put("Slam", new Move("Slam", Type.NORMAL, Attribute.PHYSICAL, 20, 80, 75));
		moveMap.put("Vine Whip", new Move("Vine Whip", Type.GRASS, Attribute.PHYSICAL, 25, 45, 100));
		moveMap.put("Stomp", new Move("Stomp", Type.NORMAL, Attribute.PHYSICAL, 20, 65, 100));
		moveMap.put("Double Kick", new Move("Double Kick", Type.FIGHTING, Attribute.PHYSICAL, 30, 30, 100));
		moveMap.put("Mega Kick", new Move("Mega Kick", Type.NORMAL, Attribute.PHYSICAL, 5, 120, 75));
		moveMap.put("Jump Kick", new Move("Jump Kick", Type.FIGHTING, Attribute.PHYSICAL, 10, 100, 95));
		moveMap.put("Rolling Kick", new Move("Rolling Kick", Type.FIGHTING, Attribute.PHYSICAL, 15, 60, 85));
		moveMap.put("Sand Attack", new Move("Sand Attack", Type.GROUND, Attribute.STATUS, 15, -1, 100));
		moveMap.put("Headbutt", new Move("Headbutt", Type.NORMAL, Attribute.PHYSICAL, 15, 70, 100));
		moveMap.put("Horn Attack", new Move("Horn Attack", Type.NORMAL, Attribute.PHYSICAL, 25, 65, 100));
		moveMap.put("Fury Attack", new Move("Fury Attack", Type.NORMAL, Attribute.PHYSICAL, 20, 15, 85));
		moveMap.put("Horn Drill", new Move("Horn Drill", Type.NORMAL, Attribute.PHYSICAL, 5, -1, -1));
		moveMap.put("Tackle", new Move("Tackle", Type.NORMAL, Attribute.PHYSICAL, 35, 50, 100));
		moveMap.put("Body Slam", new Move("Body Slam", Type.NORMAL, Attribute.PHYSICAL, 15, 85, 100));
		moveMap.put("Wrap", new Move("Wrap", Type.NORMAL, Attribute.PHYSICAL, 20, 15, 90));
		moveMap.put("Take Down", new Move("Take Down", Type.NORMAL, Attribute.PHYSICAL, 20, 90, 85));
		moveMap.put("Thrash", new Move("Thrash", Type.NORMAL, Attribute.PHYSICAL, 10, 120, 100));
		moveMap.put("Double-Edge", new Move("Double-Edge", Type.NORMAL, Attribute.PHYSICAL, 15, 120, 100));
		moveMap.put("Tail Whip", new Move("Tail Whip", Type.NORMAL, Attribute.STATUS, 30, -1, 100));
		moveMap.put("Poison Sting", new Move("Poison Sting", Type.POISON, Attribute.PHYSICAL, 35, 15, 100));
		moveMap.put("Twineedle", new Move("Twineedle", Type.BUG, Attribute.PHYSICAL, 20, 25, 100));
		moveMap.put("Pin Missile", new Move("Pin Missile", Type.BUG, Attribute.PHYSICAL, 20, 25, 95));
		moveMap.put("Leer", new Move("Leer", Type.NORMAL, Attribute.STATUS, 30, -1, 100));
		moveMap.put("Bite", new Move("Bite", Type.DARK, Attribute.PHYSICAL, 25, 60, 100));
		moveMap.put("Growl", new Move("Growl", Type.NORMAL, Attribute.STATUS, 40, -1, 100));
		moveMap.put("Roar", new Move("Roar", Type.NORMAL, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Sing", new Move("Sing", Type.NORMAL, Attribute.STATUS, 15, -1, 55));
		moveMap.put("Supersonic", new Move("Supersonic", Type.NORMAL, Attribute.STATUS, 20, -1, 55));
		moveMap.put("Sonic Boom", new Move("Sonic Boom", Type.NORMAL, Attribute.SPECIAL, 20, -1, 90));
		moveMap.put("Disable", new Move("Disable", Type.NORMAL, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Acid", new Move("Acid", Type.POISON, Attribute.SPECIAL, 30, 40, 100));
		moveMap.put("Ember", new Move("Ember", Type.FIRE, Attribute.SPECIAL, 25, 40, 100));
		moveMap.put("Flamethrower", new Move("Flamethrower", Type.FIRE, Attribute.SPECIAL, 15, 90, 100));
		moveMap.put("Mist", new Move("Mist", Type.ICE, Attribute.STATUS, 30, -1, -1));
		moveMap.put("Water Gun", new Move("Water Gun", Type.WATER, Attribute.SPECIAL, 25, 40, 100));
		moveMap.put("Hydro Pump", new Move("Hydro Pump", Type.WATER, Attribute.SPECIAL, 5, 110, 80));
		moveMap.put("Surf", new Move("Surf", Type.WATER, Attribute.SPECIAL, 15, 90, 100));
		moveMap.put("Ice Beam", new Move("Ice Beam", Type.ICE, Attribute.SPECIAL, 10, 90, 100));
		moveMap.put("Blizzard", new Move("Blizzard", Type.ICE, Attribute.SPECIAL, 5, 110, 70));
		moveMap.put("Psybeam", new Move("Psybeam", Type.PSYCHIC, Attribute.SPECIAL, 20, 65, 100));
		moveMap.put("Bubble Beam", new Move("Bubble Beam", Type.WATER, Attribute.SPECIAL, 20, 65, 100));
		moveMap.put("Aurora Beam", new Move("Aurora Beam", Type.ICE, Attribute.SPECIAL, 20, 65, 100));
		moveMap.put("Hyper Beam", new Move("Hyper Beam", Type.NORMAL, Attribute.SPECIAL, 5, 150, 90));
		moveMap.put("Peck", new Move("Peck", Type.FLYING, Attribute.PHYSICAL, 35, 35, 100));
		moveMap.put("Drill Peck", new Move("Drill Peck", Type.FLYING, Attribute.PHYSICAL, 20, 80, 100));
		moveMap.put("Submission", new Move("Submission", Type.FIGHTING, Attribute.PHYSICAL, 25, 80, 80));
		moveMap.put("Low Kick", new Move("Low Kick", Type.FIGHTING, Attribute.PHYSICAL, 20, -1, 100));
		moveMap.put("Counter", new Move("Counter", Type.FIGHTING, Attribute.PHYSICAL, 20, -1, 100));
		moveMap.put("Seismic Toss", new Move("Seismic Toss", Type.FIGHTING, Attribute.PHYSICAL, 20, -1, 100));
		moveMap.put("Strength", new Move("Strength", Type.NORMAL, Attribute.PHYSICAL, 15, 80, 100));
		moveMap.put("Absorb", new Move("Absorb", Type.GRASS, Attribute.SPECIAL, 25, 20, 100));
		moveMap.put("Mega Drain", new Move("Mega Drain", Type.GRASS, Attribute.SPECIAL, 15, 40, 100));
		moveMap.put("Leech Seed", new Move("Leech Seed", Type.GRASS, Attribute.STATUS, 10, -1, 90));
		moveMap.put("Growth", new Move("Growth", Type.NORMAL, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Razor Leaf", new Move("Razor Leaf", Type.GRASS, Attribute.PHYSICAL, 25, 55, 95));
		moveMap.put("Solar Beam", new Move("Solar Beam", Type.GRASS, Attribute.SPECIAL, 10, 120, 100));
		moveMap.put("Poison Powder", new Move("Poison Powder", Type.POISON, Attribute.STATUS, 35, -1, 75));
		moveMap.put("Stun Spore", new Move("Stun Spore", Type.GRASS, Attribute.STATUS, 30, -1, 75));
		moveMap.put("Sleep Powder", new Move("Sleep Powder", Type.GRASS, Attribute.STATUS, 15, -1, 75));
		moveMap.put("Petal Dance", new Move("Petal Dance", Type.GRASS, Attribute.SPECIAL, 10, 120, 100));
		moveMap.put("String Shot", new Move("String Shot", Type.BUG, Attribute.STATUS, 40, -1, 95));
		moveMap.put("Dragon Rage", new Move("Dragon Rage", Type.DRAGON, Attribute.SPECIAL, 10,-1, 100));
		moveMap.put("Fire Spin", new Move("Fire Spin", Type.FIRE, Attribute.SPECIAL, 15, 35, 85));
		moveMap.put("Thunder Shock", new Move("Thunder Shock", Type.ELECTRIC, Attribute.SPECIAL, 30, 40, 100));
		moveMap.put("Thunderbolt", new Move("Thunderbolt", Type.ELECTRIC, Attribute.SPECIAL, 15, 90, 100));
		moveMap.put("Thunder Wave", new Move("Thunder Wave", Type.ELECTRIC, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Thunder", new Move("Thunder", Type.ELECTRIC, Attribute.SPECIAL, 10, 110, 70));
		moveMap.put("Rock Throw", new Move("Rock Throw", Type.ROCK, Attribute.PHYSICAL, 15, 50, 90));
		moveMap.put("Earthquake", new Move("Earthquake", Type.GROUND, Attribute.PHYSICAL, 10, 100, 100));
		moveMap.put("Fissure", new Move("Fissure", Type.GROUND, Attribute.PHYSICAL, 5, -1, -1));
		moveMap.put("Dig", new Move("Dig", Type.GROUND, Attribute.PHYSICAL, 10, 80, 100));
		moveMap.put("Toxic", new Move("Toxic", Type.POISON, Attribute.STATUS, 10, -1, 90));
		moveMap.put("Confusion", new Move("Confusion", Type.PSYCHIC, Attribute.SPECIAL, 25, 50, 100));
		moveMap.put("Psychic", new Move("Psychic", Type.PSYCHIC, Attribute.SPECIAL, 10, 90, 100));
		moveMap.put("Hypnosis", new Move("Hypnosis", Type.PSYCHIC, Attribute.STATUS, 20, -1, 60));
		moveMap.put("Meditate", new Move("Meditate", Type.PSYCHIC, Attribute.STATUS, 40, -1, -1));
		moveMap.put("Agility", new Move("Agility", Type.PSYCHIC, Attribute.STATUS, 30, -1, -1));
		moveMap.put("Quick Attack", new Move("Quick Attack", Type.NORMAL, Attribute.PHYSICAL, 30, 40, 100));
		moveMap.put("Rage", new Move("Rage", Type.NORMAL, Attribute.PHYSICAL, 20, 20, 100));
		moveMap.put("Teleport", new Move("Teleport", Type.PSYCHIC, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Night Shade", new Move("Night Shade", Type.GHOST, Attribute.SPECIAL, 15, -1, 100));
		moveMap.put("Mimic", new Move("Mimic", Type.NORMAL, Attribute.STATUS, 10, -1, 100));
		moveMap.put("Screech", new Move("Screech", Type.NORMAL, Attribute.STATUS, 40, -1, 85));
		moveMap.put("Double Team", new Move("Double Team", Type.NORMAL, Attribute.STATUS, 15, -1, -1));
		moveMap.put("Recover", new Move("Recover", Type.NORMAL, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Harden", new Move("Harden", Type.NORMAL, Attribute.STATUS, 30, -1, -1));
		moveMap.put("Minimize", new Move("Minimize", Type.NORMAL, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Smokescreen", new Move("Smokescreen", Type.NORMAL, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Confuse Ray", new Move("Confuse Ray", Type.GHOST, Attribute.STATUS, 10, -1, 100));
		moveMap.put("Withdraw", new Move("Withdraw", Type.WATER, Attribute.STATUS, 40, -1, -1));
		moveMap.put("Defense Curl", new Move("Defense Curl", Type.NORMAL, Attribute.STATUS, 40, -1, -1));
		moveMap.put("Barrier", new Move("Barrier", Type.PSYCHIC, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Light Screen", new Move("Light Screen", Type.PSYCHIC, Attribute.STATUS, 30, -1, -1));
		moveMap.put("Haze", new Move("Haze", Type.ICE, Attribute.STATUS, 30, -1, -1));
		moveMap.put("Reflect", new Move("Reflect", Type.PSYCHIC, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Focus Energy", new Move("Focus Energy", Type.NORMAL, Attribute.STATUS, 30, -1, -1));
		moveMap.put("Bide", new Move("Bide", Type.NORMAL, Attribute.PHYSICAL, 10, -1, 100));
		moveMap.put("Metronome", new Move("Metronome", Type.NORMAL, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Mirror Move", new Move("Mirror Move", Type.FLYING, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Self-Destruct", new Move("Self-Destruct", Type.NORMAL, Attribute.PHYSICAL, 5, 200, 100));
		moveMap.put("Egg Bomb", new Move("Egg Bomb", Type.NORMAL, Attribute.PHYSICAL, 10, 100, 75));
		moveMap.put("Lick", new Move("Lick", Type.GHOST, Attribute.PHYSICAL, 30, 30, 100));
		moveMap.put("Smog", new Move("Smog", Type.POISON, Attribute.SPECIAL, 20, 30, 70));
		moveMap.put("Sludge", new Move("Sludge", Type.POISON, Attribute.SPECIAL, 20, 65, 100));
		moveMap.put("Bone Club", new Move("Bone Club", Type.GROUND, Attribute.PHYSICAL, 20, 65, 85));
		moveMap.put("Fire Blast", new Move("Fire Blast", Type.FIRE, Attribute.SPECIAL, 5, 110, 85));
		moveMap.put("Waterfall", new Move("Waterfall", Type.WATER, Attribute.PHYSICAL, 15, 80, 100));
		moveMap.put("Clamp", new Move("Clamp", Type.WATER, Attribute.PHYSICAL, 10, 35, 85));
		moveMap.put("Swift", new Move("Swift", Type.NORMAL, Attribute.SPECIAL, 20, 60, -1));
		moveMap.put("Skull Bash", new Move("Skull Bash", Type.NORMAL, Attribute.PHYSICAL, 10, 130, 100));
		moveMap.put("Spike Cannon", new Move("Spike Cannon", Type.NORMAL, Attribute.PHYSICAL, 15, 20, 100));
		moveMap.put("Constrict", new Move("Constrict", Type.NORMAL, Attribute.PHYSICAL, 35, 10, 100));
		moveMap.put("Amnesia", new Move("Amnesia", Type.PSYCHIC, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Kinesis", new Move("Kinesis", Type.PSYCHIC, Attribute.STATUS, 15, -1, 80));
		moveMap.put("Soft-Boiled", new Move("Soft-Boiled", Type.NORMAL, Attribute.STATUS, 10, -1, -1));
		moveMap.put("High Jump Kick", new Move("High Jump Kick", Type.FIGHTING, Attribute.PHYSICAL, 10, 130, 90));
		moveMap.put("Glare", new Move("Glare", Type.NORMAL, Attribute.STATUS, 30, -1, 100));
		moveMap.put("Dream Eater", new Move("Dream Eater", Type.PSYCHIC, Attribute.SPECIAL, 15, 100, 100));
		moveMap.put("Poison Gas", new Move("Poison Gas", Type.POISON, Attribute.STATUS, 40, -1, 90));
		moveMap.put("Barrage", new Move("Barrage", Type.NORMAL, Attribute.PHYSICAL, 20, 15, 85));
		moveMap.put("Leech Life", new Move("Leech Life", Type.BUG, Attribute.PHYSICAL, 15, 20, 100));
		moveMap.put("Lovely Kiss", new Move("Lovely Kiss", Type.NORMAL, Attribute.STATUS, 10, -1, 75));
		moveMap.put("Sky Attack", new Move("Sky Attack", Type.FLYING, Attribute.PHYSICAL, 5, 140, 90));
		moveMap.put("Transform", new Move("Transform", Type.NORMAL, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Bubble", new Move("Bubble", Type.WATER, Attribute.SPECIAL, 30, 40, 100));
		moveMap.put("Dizzy Punch", new Move("Dizzy Punch", Type.NORMAL, Attribute.PHYSICAL, 10, 70, 100));
		moveMap.put("Spore", new Move("Spore", Type.GRASS, Attribute.STATUS, 15, -1, 100));
		moveMap.put("Flash", new Move("Flash", Type.NORMAL, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Psywave", new Move("Psywave", Type.PSYCHIC, Attribute.SPECIAL, 15, -1, 100));
		moveMap.put("Splash", new Move("Splash", Type.NORMAL, Attribute.STATUS, 40, -1, -1));
		moveMap.put("Acid Armor", new Move("Acid Armor", Type.POISON, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Crabhammer", new Move("Crabhammer", Type.WATER, Attribute.PHYSICAL, 10, 100, 90));
		moveMap.put("Explosion", new Move("Explosion", Type.NORMAL, Attribute.PHYSICAL, 5, 250, 100));
		moveMap.put("Fury Swipes", new Move("Fury Swipes", Type.NORMAL, Attribute.PHYSICAL, 15, 18, 80));
		moveMap.put("Bonemerang", new Move("Bonemerang", Type.GROUND, Attribute.PHYSICAL, 10, 50, 90));
		moveMap.put("Rest", new Move("Rest", Type.PSYCHIC, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Rock Slide", new Move("Rock Slide", Type.ROCK, Attribute.PHYSICAL, 10, 75, 90));
		moveMap.put("Hyper Fang", new Move("Hyper Fang", Type.NORMAL, Attribute.PHYSICAL, 15, 80, 90));
		moveMap.put("Sharpen", new Move("Sharpen", Type.NORMAL, Attribute.STATUS, 30, -1, -1));
		moveMap.put("Conversion", new Move("Conversion", Type.NORMAL, Attribute.STATUS, 30, -1, -1));
		moveMap.put("Tri Attack", new Move("Tri Attack", Type.NORMAL, Attribute.SPECIAL, 10, 80, 100));
		moveMap.put("Super Fang", new Move("Super Fang", Type.NORMAL, Attribute.PHYSICAL, 10, -1, 90));
		moveMap.put("Slash", new Move("Slash", Type.NORMAL, Attribute.PHYSICAL, 20, 70, 100));
		moveMap.put("Substitute", new Move("Substitute", Type.NORMAL, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Struggle", new Move("Struggle", Type.NORMAL, Attribute.PHYSICAL, 1, 50, -1));
		moveMap.put("Sketch", new Move("Sketch", Type.NORMAL, Attribute.STATUS, 1, -1, -1));
		moveMap.put("Triple Kick", new Move("Triple Kick", Type.FIGHTING, Attribute.PHYSICAL, 10, 10, 90));
		moveMap.put("Thief", new Move("Thief", Type.DARK, Attribute.PHYSICAL, 25, 60, 100));
		moveMap.put("Spider Web", new Move("Spider Web", Type.BUG, Attribute.STATUS, 10, -1, 100));
		moveMap.put("Mind Reader", new Move("Mind Reader", Type.NORMAL, Attribute.STATUS, 5, -1, 100));
		moveMap.put("Nightmare", new Move("Nightmare", Type.GHOST, Attribute.STATUS, 15, -1, 100));
		moveMap.put("Flame Wheel", new Move("Flame Wheel", Type.FIRE, Attribute.PHYSICAL, 25, 60, 100));
		moveMap.put("Snore", new Move("Snore", Type.NORMAL, Attribute.SPECIAL, 15, 50, 100));
		moveMap.put("Curse", new Move("Curse", Type.GHOST, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Flail", new Move("Flail", Type.NORMAL, Attribute.PHYSICAL, 15, -1, 100));
		moveMap.put("Conversion 2", new Move("Conversion 2", Type.NORMAL, Attribute.STATUS, 30, -1, 100));
		moveMap.put("Aeroblast", new Move("Aeroblast", Type.FLYING, Attribute.SPECIAL, 5, 100, 95));
		moveMap.put("Cotton Spore", new Move("Cotton Spore", Type.GRASS, Attribute.STATUS, 40, -1, 100));
		moveMap.put("Reversal", new Move("Reversal", Type.FIGHTING, Attribute.PHYSICAL, 15, -1, 100));
		moveMap.put("Spite", new Move("Spite", Type.GHOST, Attribute.STATUS, 10, -1, 100));
		moveMap.put("Powder Snow", new Move("Powder Snow", Type.ICE, Attribute.SPECIAL, 25, 40, 100));
		moveMap.put("Protect", new Move("Protect", Type.NORMAL, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Mach Punch", new Move("Mach Punch", Type.FIGHTING, Attribute.PHYSICAL, 30, 40, 100));
		moveMap.put("Scary Face", new Move("Scary Face", Type.NORMAL, Attribute.STATUS, 10, -1, 100));
		moveMap.put("Feint Attack", new Move("Feint Attack", Type.DARK, Attribute.PHYSICAL, 20, 60, -1));
		moveMap.put("Sweet Kiss", new Move("Sweet Kiss", Type.FAIRY, Attribute.STATUS, 10, -1, 75));
		moveMap.put("Belly Drum", new Move("Belly Drum", Type.NORMAL, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Sludge Bomb", new Move("Sludge Bomb", Type.POISON, Attribute.SPECIAL, 10, 90, 100));
		moveMap.put("Mud-Slap", new Move("Mud-Slap", Type.GROUND, Attribute.SPECIAL, 10, 20, 100));
		moveMap.put("Octazooka", new Move("Octazooka", Type.WATER, Attribute.SPECIAL, 10, 65, 85));
		moveMap.put("Spikes", new Move("Spikes", Type.GROUND, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Zap Cannon", new Move("Zap Cannon", Type.ELECTRIC, Attribute.SPECIAL, 5, 120, 50));
		moveMap.put("Foresight", new Move("Foresight", Type.NORMAL, Attribute.STATUS, 40, -1, 100));
		moveMap.put("Destiny Bond", new Move("Destiny Bond", Type.GHOST, Attribute.STATUS, 5, -1, -1));
		moveMap.put("Perish Song", new Move("Perish Song", Type.NORMAL, Attribute.STATUS, 5, -1, -1));
		moveMap.put("Icy Wind", new Move("Icy Wind", Type.ICE, Attribute.SPECIAL, 15, 55, 95));
		moveMap.put("Detect", new Move("Detect", Type.FIGHTING, Attribute.STATUS, 5, -1, -1));
		moveMap.put("Bone Rush", new Move("Bone Rush", Type.GROUND, Attribute.PHYSICAL, 10, 25, 90));
		moveMap.put("Lock-On", new Move("Lock-On", Type.NORMAL, Attribute.STATUS, 5, -1, 100));
		moveMap.put("Outrage", new Move("Outrage", Type.DRAGON, Attribute.PHYSICAL, 10, 120, 100));
		moveMap.put("Sandstorm", new Move("Sandstorm", Type.ROCK, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Giga Drain", new Move("Giga Drain", Type.GRASS, Attribute.SPECIAL, 10, 75, 100));
		moveMap.put("Endure", new Move("Endure", Type.NORMAL, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Charm", new Move("Charm", Type.FAIRY, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Rollout", new Move("Rollout", Type.ROCK, Attribute.PHYSICAL, 20, 30, 90));
		moveMap.put("False Swipe", new Move("False Swipe", Type.NORMAL, Attribute.PHYSICAL, 40, 40, 100));
		moveMap.put("Swagger", new Move("Swagger", Type.NORMAL, Attribute.STATUS, 15, -1, 90));
		moveMap.put("Milk Drink", new Move("Milk Drink", Type.NORMAL, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Spark", new Move("Spark", Type.ELECTRIC, Attribute.PHYSICAL, 20, 65, 100));
		moveMap.put("Fury Cutter", new Move("Fury Cutter", Type.BUG, Attribute.PHYSICAL, 20, 40, 95));
		moveMap.put("Steel Wing", new Move("Steel Wing", Type.STEEL, Attribute.PHYSICAL, 25, 70, 90));
		moveMap.put("Mean Look", new Move("Mean Look", Type.NORMAL, Attribute.STATUS, 5, -1, 100));
		moveMap.put("Attract", new Move("Attract", Type.NORMAL, Attribute.STATUS, 15, -1, 100));
		moveMap.put("Sleep Talk", new Move("Sleep Talk", Type.NORMAL, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Heal Bell", new Move("Heal Bell", Type.NORMAL, Attribute.STATUS, 5, -1, -1));
		moveMap.put("Return", new Move("Return", Type.NORMAL, Attribute.PHYSICAL, 20, -1, 100));
		moveMap.put("Present", new Move("Present", Type.NORMAL, Attribute.PHYSICAL, 15, -1, 90));
		moveMap.put("Frustration", new Move("Frustration", Type.NORMAL, Attribute.PHYSICAL, 20, -1, 100));
		moveMap.put("Safeguard", new Move("Safeguard", Type.NORMAL, Attribute.STATUS, 25, -1, -1));
		moveMap.put("Pain Split", new Move("Pain Split", Type.NORMAL, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Sacred Fire", new Move("Sacred Fire", Type.FIRE, Attribute.PHYSICAL, 5, 100, 95));
		moveMap.put("Magnitude", new Move("Magnitude", Type.GROUND, Attribute.PHYSICAL, 30, -1, 100));
		moveMap.put("Dynamic Punch", new Move("Dynamic Punch", Type.FIGHTING, Attribute.PHYSICAL, 5, 100, 50));
		moveMap.put("Megahorn", new Move("Megahorn", Type.BUG, Attribute.PHYSICAL, 10, 120, 85));
		moveMap.put("Dragon Breath", new Move("Dragon Breath", Type.DRAGON, Attribute.SPECIAL, 20, 60, 100));
		moveMap.put("Baton Pass", new Move("Baton Pass", Type.NORMAL, Attribute.STATUS, 40, -1, -1));
		moveMap.put("Encore", new Move("Encore", Type.NORMAL, Attribute.STATUS, 5, -1, 100));
		moveMap.put("Pursuit", new Move("Pursuit", Type.DARK, Attribute.PHYSICAL, 20, 40, 100));
		moveMap.put("Rapid Spin", new Move("Rapid Spin", Type.NORMAL, Attribute.PHYSICAL, 40, 20, 100));
		moveMap.put("Sweet Scent", new Move("Sweet Scent", Type.NORMAL, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Iron Tail", new Move("Iron Tail", Type.STEEL, Attribute.PHYSICAL, 15, 100, 75));
		moveMap.put("Metal Claw", new Move("Metal Claw", Type.STEEL, Attribute.PHYSICAL, 35, 50, 95));
		moveMap.put("Vital Throw", new Move("Vital Throw", Type.FIGHTING, Attribute.PHYSICAL, 10, 70, -1));
		moveMap.put("Morning Sun", new Move("Morning Sun", Type.NORMAL, Attribute.STATUS, 5, -1, -1));
		moveMap.put("Synthesis", new Move("Synthesis", Type.GRASS, Attribute.STATUS, 5, -1, -1));
		moveMap.put("Moonlight", new Move("Moonlight", Type.FAIRY, Attribute.STATUS, 5, -1, -1));
		moveMap.put("Hidden Power", new Move("Hidden Power", Type.NORMAL, Attribute.SPECIAL, 15, 60, 100));
		moveMap.put("Cross Chop", new Move("Cross Chop", Type.FIGHTING, Attribute.PHYSICAL, 5, 100, 80));
		moveMap.put("Twister", new Move("Twister", Type.DRAGON, Attribute.SPECIAL, 20, 40, 100));
		moveMap.put("Rain Dance", new Move("Rain Dance", Type.WATER, Attribute.STATUS, 5, -1, -1));
		moveMap.put("Sunny Day", new Move("Sunny Day", Type.FIRE, Attribute.STATUS, 5, -1, -1));
		moveMap.put("Crunch", new Move("Crunch", Type.DARK, Attribute.PHYSICAL, 15, 80, 100));
		moveMap.put("Mirror Coat", new Move("Mirror Coat", Type.PSYCHIC, Attribute.SPECIAL, 20, -1, 100));
		moveMap.put("Psych Up", new Move("Psych Up", Type.NORMAL, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Extreme Speed", new Move("Extreme Speed", Type.NORMAL, Attribute.PHYSICAL, 5, 80, 100));
		moveMap.put("Ancient Power", new Move("Ancient Power", Type.ROCK, Attribute.SPECIAL, 5, 60, 100));
		moveMap.put("Shadow Ball", new Move("Shadow Ball", Type.GHOST, Attribute.SPECIAL, 15, 80, 100));
		moveMap.put("Future Sight", new Move("Future Sight", Type.PSYCHIC, Attribute.SPECIAL, 10, 120, 100));
		moveMap.put("Rock Smash", new Move("Rock Smash", Type.FIGHTING, Attribute.PHYSICAL, 15, 40, 100));
		moveMap.put("Whirlpool", new Move("Whirlpool", Type.WATER, Attribute.SPECIAL, 15, 35, 85));
		moveMap.put("Beat Up", new Move("Beat Up", Type.DARK, Attribute.PHYSICAL, 10, -1, 100));
		moveMap.put("Fake Out", new Move("Fake Out", Type.NORMAL, Attribute.PHYSICAL, 10, 40, 100));
		moveMap.put("Uproar", new Move("Uproar", Type.NORMAL, Attribute.SPECIAL, 10, 90, 100));
		moveMap.put("Stockpile", new Move("Stockpile", Type.NORMAL, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Spit Up", new Move("Spit Up", Type.NORMAL, Attribute.SPECIAL, 10, -1, 100));
		moveMap.put("Swallow", new Move("Swallow", Type.NORMAL, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Heat Wave", new Move("Heat Wave", Type.FIRE, Attribute.SPECIAL, 10, 95, 90));
		moveMap.put("Hail", new Move("Hail", Type.ICE, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Torment", new Move("Torment", Type.DARK, Attribute.STATUS, 15, -1, 100));
		moveMap.put("Flatter", new Move("Flatter", Type.DARK, Attribute.STATUS, 15, -1, 100));
		moveMap.put("Will-O-Wisp", new Move("Will-O-Wisp", Type.FIRE, Attribute.STATUS, 15, -1, 85));
		moveMap.put("Memento", new Move("Memento", Type.DARK, Attribute.STATUS, 10, -1, 100));
		moveMap.put("Facade", new Move("Facade", Type.NORMAL, Attribute.PHYSICAL, 20, 70, 100));
		moveMap.put("Focus Punch", new Move("Focus Punch", Type.FIGHTING, Attribute.PHYSICAL, 20, 150, 100));
		moveMap.put("Smelling Salts", new Move("Smelling Salts", Type.NORMAL, Attribute.PHYSICAL, 10, 70, 100));
		moveMap.put("Follow Me", new Move("Follow Me", Type.NORMAL, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Nature Power", new Move("Nature Power", Type.NORMAL, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Charge", new Move("Charge", Type.ELECTRIC, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Taunt", new Move("Taunt", Type.DARK, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Helping Hand", new Move("Helping Hand", Type.NORMAL, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Trick", new Move("Trick", Type.PSYCHIC, Attribute.STATUS, 10, -1, 100));
		moveMap.put("Role Play", new Move("Role Play", Type.PSYCHIC, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Wish", new Move("Wish", Type.NORMAL, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Assist", new Move("Assist", Type.NORMAL, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Ingrain", new Move("Ingrain", Type.GRASS, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Superpower", new Move("Superpower", Type.FIGHTING, Attribute.PHYSICAL, 5, 120, 100));
		moveMap.put("Magic Coat", new Move("Magic Coat", Type.PSYCHIC, Attribute.STATUS, 15, -1, -1));
		moveMap.put("Recycle", new Move("Recycle", Type.NORMAL, Attribute.STATUS, 10, -1, 100));
		moveMap.put("Revenge", new Move("Revenge", Type.FIGHTING, Attribute.PHYSICAL, 10, 60, 100));
		moveMap.put("Brick Break", new Move("Brick Break", Type.FIGHTING, Attribute.PHYSICAL, 15, 75, 100));
		moveMap.put("Yawn", new Move("Yawn", Type.NORMAL, Attribute.STATUS, 10, -1, 100));
		moveMap.put("Knock Off", new Move("Knock Off", Type.DARK, Attribute.PHYSICAL, 20, 65, 100));
		moveMap.put("Endeavor", new Move("Endeavor", Type.NORMAL, Attribute.PHYSICAL, 5, -1, 100));
		moveMap.put("Eruption", new Move("Eruption", Type.FIRE, Attribute.SPECIAL, 5, -1, 100));
		moveMap.put("Skill Swap", new Move("Skill Swap", Type.PSYCHIC, Attribute.STATUS, 10, -1, 100));
		moveMap.put("Imprison", new Move("Imprison", Type.PSYCHIC, Attribute.STATUS, 10, -1, 100));
		moveMap.put("Refresh", new Move("Refresh", Type.NORMAL, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Grudge", new Move("Grudge", Type.GHOST, Attribute.STATUS, 5, -1, 100));
		moveMap.put("Snatch", new Move("Snatch", Type.DARK, Attribute.STATUS, 10, -1, 100));
		moveMap.put("Secret Power", new Move("Secret Power", Type.NORMAL, Attribute.PHYSICAL, 20, 70, 100));
		moveMap.put("Dive", new Move("Dive", Type.WATER, Attribute.PHYSICAL, 10, 80, 100));
		moveMap.put("Arm Thrust", new Move("Arm Thrust", Type.FIGHTING, Attribute.PHYSICAL, 20, 15, 100));
		moveMap.put("Camouflage", new Move("Camouflage", Type.NORMAL, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Tail Glow", new Move("Tail Glow", Type.BUG, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Luster Purge", new Move("Luster Purge", Type.PSYCHIC, Attribute.SPECIAL, 5, 70, 100));
		moveMap.put("Mist Ball", new Move("Mist Ball", Type.PSYCHIC, Attribute.SPECIAL, 5, 70, 100));
		moveMap.put("Feather Dance", new Move("Feather Dance", Type.FLYING, Attribute.STATUS, 15, -1, 100));
		moveMap.put("Teeter Dance", new Move("Teeter Dance", Type.NORMAL, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Blaze Kick", new Move("Blaze Kick", Type.FIRE, Attribute.PHYSICAL, 10, 85, 90));
		moveMap.put("Mud Sport", new Move("Mud Sport", Type.GROUND, Attribute.STATUS, 15, -1, 100));
		moveMap.put("Ice Ball", new Move("Ice Ball", Type.ICE, Attribute.PHYSICAL, 20, 30, 90));
		moveMap.put("Needle Arm", new Move("Needle Arm", Type.GRASS, Attribute.PHYSICAL, 15, 60, 100));
		moveMap.put("Slack Off", new Move("Slack Off", Type.NORMAL, Attribute.STATUS, 10, -1, 100));
		moveMap.put("Hyper Voice", new Move("Hyper Voice", Type.NORMAL, Attribute.SPECIAL, 10, 90, 100));
		moveMap.put("Poison Fang", new Move("Poison Fang", Type.POISON, Attribute.PHYSICAL, 15, 50, 100));
		moveMap.put("Crush Claw", new Move("Crush Claw", Type.NORMAL, Attribute.PHYSICAL, 10, 75, 95));
		moveMap.put("Blast Burn", new Move("Blast Burn", Type.FIRE, Attribute.SPECIAL, 5, 150, 90));
		moveMap.put("Hydro Cannon", new Move("Hydro Cannon", Type.WATER, Attribute.SPECIAL, 5, 150, 90));
		moveMap.put("Meteor Mash", new Move("Meteor Mash", Type.STEEL, Attribute.PHYSICAL, 10, 90, 90));
		moveMap.put("Astonish", new Move("Astonish", Type.GHOST, Attribute.PHYSICAL, 15, 30, 100));
		moveMap.put("Weather Ball", new Move("Weather Ball", Type.NORMAL, Attribute.SPECIAL, 10, 50, 100));
		moveMap.put("Aromatherapy", new Move("Aromatherapy", Type.GRASS, Attribute.STATUS, 5, -1, -1));
		moveMap.put("Fake Tears", new Move("Fake Tears", Type.DARK, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Air Cutter", new Move("Air Cutter", Type.FLYING, Attribute.SPECIAL, 25, 60, 95));
		moveMap.put("Overheat", new Move("Overheat", Type.FIRE, Attribute.SPECIAL, 5, 130, 90));
		moveMap.put("Odor Sleuth", new Move("Odor Sleuth", Type.NORMAL, Attribute.STATUS, 40, -1, 100));
		moveMap.put("Rock Tomb", new Move("Rock Tomb", Type.ROCK, Attribute.PHYSICAL, 15, 60, 95));
		moveMap.put("Silver Wind", new Move("Silver Wind", Type.BUG, Attribute.SPECIAL, 5, 60, 100));
		moveMap.put("Metal Sound", new Move("Metal Sound", Type.STEEL, Attribute.STATUS, 40, -1, 85));
		moveMap.put("Grass Whistle", new Move("Grass Whistle", Type.GRASS, Attribute.STATUS, 15, -1, 55));
		moveMap.put("Tickle", new Move("Tickle", Type.NORMAL, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Cosmic Power", new Move("Cosmic Power", Type.PSYCHIC, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Water Spout", new Move("Water Spout", Type.WATER, Attribute.SPECIAL, 5, -1, 100));
		moveMap.put("Signal Beam", new Move("Signal Beam", Type.BUG, Attribute.SPECIAL, 15, 75, 100));
		moveMap.put("Shadow Punch", new Move("Shadow Punch", Type.GHOST, Attribute.PHYSICAL, 20, 60, -1));
		moveMap.put("Extrasensory", new Move("Extrasensory", Type.PSYCHIC, Attribute.SPECIAL, 20, 80, 100));
		moveMap.put("Sky Uppercut", new Move("Sky Uppercut", Type.FIGHTING, Attribute.PHYSICAL, 15, 85, 90));
		moveMap.put("Sand Tomb", new Move("Sand Tomb", Type.GROUND, Attribute.PHYSICAL, 15, 35, 85));
		moveMap.put("Sheer Cold", new Move("Sheer Cold", Type.ICE, Attribute.SPECIAL, 5, -1, -1));
		moveMap.put("Muddy Water", new Move("Muddy Water", Type.WATER, Attribute.SPECIAL, 10, 90, 85));
		moveMap.put("Bullet Seed", new Move("Bullet Seed", Type.GRASS, Attribute.PHYSICAL, 30, 25, 100));
		moveMap.put("Aerial Ace", new Move("Aerial Ace", Type.FLYING, Attribute.PHYSICAL, 20, 60, -1));
		moveMap.put("Icicle Spear", new Move("Icicle Spear", Type.ICE, Attribute.PHYSICAL, 30, 25, 100));
		moveMap.put("Iron Defense", new Move("Iron Defense", Type.STEEL, Attribute.STATUS, 15, -1, -1));
		moveMap.put("Block", new Move("Block", Type.NORMAL, Attribute.STATUS, 5, -1, 100));
		moveMap.put("Howl", new Move("Howl", Type.NORMAL, Attribute.STATUS, 40, -1, -1));
		moveMap.put("Dragon Claw", new Move("Dragon Claw", Type.DRAGON, Attribute.PHYSICAL, 15, 80, 100));
		moveMap.put("Frenzy Plant", new Move("Frenzy Plant", Type.GRASS, Attribute.SPECIAL, 5, 150, 90));
		moveMap.put("Bulk Up", new Move("Bulk Up", Type.FIGHTING, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Bounce", new Move("Bounce", Type.FLYING, Attribute.PHYSICAL, 5, 85, 85));
		moveMap.put("Mud Shot", new Move("Mud Shot", Type.GROUND, Attribute.SPECIAL, 15, 55, 95));
		moveMap.put("Poison Tail", new Move("Poison Tail", Type.POISON, Attribute.PHYSICAL, 25, 50, 100));
		moveMap.put("Covet", new Move("Covet", Type.NORMAL, Attribute.PHYSICAL, 25, 60, 100));
		moveMap.put("Volt Tackle", new Move("Volt Tackle", Type.ELECTRIC, Attribute.PHYSICAL, 15, 120, 100));
		moveMap.put("Magical Leaf", new Move("Magical Leaf", Type.GRASS, Attribute.SPECIAL, 20, 60, -1));
		moveMap.put("Water Sport", new Move("Water Sport", Type.WATER, Attribute.STATUS, 15, -1, 100));
		moveMap.put("Calm Mind", new Move("Calm Mind", Type.PSYCHIC, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Leaf Blade", new Move("Leaf Blade", Type.GRASS, Attribute.PHYSICAL, 15, 90, 100));
		moveMap.put("Dragon Dance", new Move("Dragon Dance", Type.DRAGON, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Rock Blast", new Move("Rock Blast", Type.ROCK, Attribute.PHYSICAL, 10, 25, 90));
		moveMap.put("Shock Wave", new Move("Shock Wave", Type.ELECTRIC, Attribute.SPECIAL, 20, 60, -1));
		moveMap.put("Water Pulse", new Move("Water Pulse", Type.WATER, Attribute.SPECIAL, 20, 60, 100));
		moveMap.put("Doom Desire", new Move("Doom Desire", Type.STEEL, Attribute.SPECIAL, 5, 140, 100));
		moveMap.put("Psycho Boost", new Move("Psycho Boost", Type.PSYCHIC, Attribute.SPECIAL, 5, 140, 90));
		moveMap.put("Roost", new Move("Roost", Type.FLYING, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Gravity", new Move("Gravity", Type.PSYCHIC, Attribute.STATUS, 5, -1, -1));
		moveMap.put("Miracle Eye", new Move("Miracle Eye", Type.PSYCHIC, Attribute.STATUS, 40, -1, -1));
		moveMap.put("Wake-Up Slap", new Move("Wake-Up Slap", Type.FIGHTING, Attribute.PHYSICAL, 10, 70, 100));
		moveMap.put("Hammer Arm", new Move("Hammer Arm", Type.FIGHTING, Attribute.PHYSICAL, 10, 100, 90));
		moveMap.put("Gyro Ball", new Move("Gyro Ball", Type.STEEL, Attribute.PHYSICAL, 5, -1, 100));
		moveMap.put("Healing Wish", new Move("Healing Wish", Type.PSYCHIC, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Brine", new Move("Brine", Type.WATER, Attribute.SPECIAL, 10, 65, 100));
		moveMap.put("Natural Gift", new Move("Natural Gift", Type.NORMAL, Attribute.PHYSICAL, 15, -1, 100));
		moveMap.put("Feint", new Move("Feint", Type.NORMAL, Attribute.PHYSICAL, 10, 30, 100));
		moveMap.put("Pluck", new Move("Pluck", Type.FLYING, Attribute.PHYSICAL, 20, 60, 100));
		moveMap.put("Tailwind", new Move("Tailwind", Type.FLYING, Attribute.STATUS, 15, -1, -1));
		moveMap.put("Acupressure", new Move("Acupressure", Type.NORMAL, Attribute.STATUS, 30, -1, -1));
		moveMap.put("Metal Burst", new Move("Metal Burst", Type.STEEL, Attribute.PHYSICAL, 10, -1, 100));
		moveMap.put("U-turn", new Move("U-turn", Type.BUG, Attribute.PHYSICAL, 20, 70, 100));
		moveMap.put("Close Combat", new Move("Close Combat", Type.FIGHTING, Attribute.PHYSICAL, 5, 120, 100));
		moveMap.put("Payback", new Move("Payback", Type.DARK, Attribute.PHYSICAL, 10, 50, 100));
		moveMap.put("Assurance", new Move("Assurance", Type.DARK, Attribute.PHYSICAL, 10, 60, 100));
		moveMap.put("Embargo", new Move("Embargo", Type.DARK, Attribute.STATUS, 15, -1, 100));
		moveMap.put("Fling", new Move("Fling", Type.DARK, Attribute.PHYSICAL, 10, -1, 100));
		moveMap.put("Psycho Shift", new Move("Psycho Shift", Type.PSYCHIC, Attribute.STATUS, 10, -1, 100));
		moveMap.put("Trump Card", new Move("Trump Card", Type.NORMAL, Attribute.SPECIAL, 5, -1, -1));
		moveMap.put("Heal Block", new Move("Heal Block", Type.PSYCHIC, Attribute.STATUS, 15, -1, 100));
		moveMap.put("Wring Out", new Move("Wring Out", Type.NORMAL, Attribute.SPECIAL, 5, -1, 100));
		moveMap.put("Power Trick", new Move("Power Trick", Type.PSYCHIC, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Gastro Acid", new Move("Gastro Acid", Type.POISON, Attribute.STATUS, 10, -1, 100));
		moveMap.put("Lucky Chant", new Move("Lucky Chant", Type.NORMAL, Attribute.STATUS, 30, -1, -1));
		moveMap.put("Me First", new Move("Me First", Type.NORMAL, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Copycat", new Move("Copycat", Type.NORMAL, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Power Swap", new Move("Power Swap", Type.PSYCHIC, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Guard Swap", new Move("Guard Swap", Type.PSYCHIC, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Punishment", new Move("Punishment", Type.DARK, Attribute.PHYSICAL, 5, -1, 100));
		moveMap.put("Last Resort", new Move("Last Resort", Type.NORMAL, Attribute.PHYSICAL, 5, 140, 100));
		moveMap.put("Worry Seed", new Move("Worry Seed", Type.GRASS, Attribute.STATUS, 10, -1, 100));
		moveMap.put("Sucker Punch", new Move("Sucker Punch", Type.DARK, Attribute.PHYSICAL, 5, 80, 100));
		moveMap.put("Toxic Spikes", new Move("Toxic Spikes", Type.POISON, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Heart Swap", new Move("Heart Swap", Type.PSYCHIC, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Aqua Ring", new Move("Aqua Ring", Type.WATER, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Magnet Rise", new Move("Magnet Rise", Type.ELECTRIC, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Flare Blitz", new Move("Flare Blitz", Type.FIRE, Attribute.PHYSICAL, 15, 120, 100));
		moveMap.put("Force Palm", new Move("Force Palm", Type.FIGHTING, Attribute.PHYSICAL, 10, 60, 100));
		moveMap.put("Aura Sphere", new Move("Aura Sphere", Type.FIGHTING, Attribute.SPECIAL, 20, 80, -1));
		moveMap.put("Rock Polish", new Move("Rock Polish", Type.ROCK, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Poison Jab", new Move("Poison Jab", Type.POISON, Attribute.PHYSICAL, 20, 80, 100));
		moveMap.put("Dark Pulse", new Move("Dark Pulse", Type.DARK, Attribute.SPECIAL, 15, 80, 100));
		moveMap.put("Night Slash", new Move("Night Slash", Type.DARK, Attribute.PHYSICAL, 15, 70, 100));
		moveMap.put("Aqua Tail", new Move("Aqua Tail", Type.WATER, Attribute.PHYSICAL, 10, 90, 90));
		moveMap.put("Seed Bomb", new Move("Seed Bomb", Type.GRASS, Attribute.PHYSICAL, 15, 80, 100));
		moveMap.put("Air Slash", new Move("Air Slash", Type.FLYING, Attribute.SPECIAL, 15, 75, 95));
		moveMap.put("X-Scissor", new Move("X-Scissor", Type.BUG, Attribute.PHYSICAL, 15, 80, 100));
		moveMap.put("Bug Buzz", new Move("Bug Buzz", Type.BUG, Attribute.SPECIAL, 10, 90, 100));
		moveMap.put("Dragon Pulse", new Move("Dragon Pulse", Type.DRAGON, Attribute.SPECIAL, 10, 85, 100));
		moveMap.put("Dragon Rush", new Move("Dragon Rush", Type.DRAGON, Attribute.PHYSICAL, 10, 100, 75));
		moveMap.put("Power Gem", new Move("Power Gem", Type.ROCK, Attribute.SPECIAL, 20, 80, 100));
		moveMap.put("Drain Punch", new Move("Drain Punch", Type.FIGHTING, Attribute.PHYSICAL, 10, 75, 100));
		moveMap.put("Vacuum Wave", new Move("Vacuum Wave", Type.FIGHTING, Attribute.SPECIAL, 30, 40, 100));
		moveMap.put("Focus Blast", new Move("Focus Blast", Type.FIGHTING, Attribute.SPECIAL, 5, 120, 70));
		moveMap.put("Energy Ball", new Move("Energy Ball", Type.GRASS, Attribute.SPECIAL, 10, 90, 100));
		moveMap.put("Brave Bird", new Move("Brave Bird", Type.FLYING, Attribute.PHYSICAL, 15, 120, 100));
		moveMap.put("Earth Power", new Move("Earth Power", Type.GROUND, Attribute.SPECIAL, 10, 90, 100));
		moveMap.put("Switcheroo", new Move("Switcheroo", Type.DARK, Attribute.STATUS, 10, -1, 100));
		moveMap.put("Giga Impact", new Move("Giga Impact", Type.NORMAL, Attribute.PHYSICAL, 5, 150, 90));
		moveMap.put("Nasty Plot", new Move("Nasty Plot", Type.DARK, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Bullet Punch", new Move("Bullet Punch", Type.STEEL, Attribute.PHYSICAL, 30, 40, 100));
		moveMap.put("Avalanche", new Move("Avalanche", Type.ICE, Attribute.PHYSICAL, 10, 60, 100));
		moveMap.put("Ice Shard", new Move("Ice Shard", Type.ICE, Attribute.PHYSICAL, 30, 40, 100));
		moveMap.put("Shadow Claw", new Move("Shadow Claw", Type.GHOST, Attribute.PHYSICAL, 15, 70, 100));
		moveMap.put("Thunder Fang", new Move("Thunder Fang", Type.ELECTRIC, Attribute.PHYSICAL, 15, 65, 95));
		moveMap.put("Ice Fang", new Move("Ice Fang", Type.ICE, Attribute.PHYSICAL, 15, 65, 95));
		moveMap.put("Fire Fang", new Move("Fire Fang", Type.FIRE, Attribute.PHYSICAL, 15, 65, 95));
		moveMap.put("Shadow Sneak", new Move("Shadow Sneak", Type.GHOST, Attribute.PHYSICAL, 30, 40, 100));
		moveMap.put("Mud Bomb", new Move("Mud Bomb", Type.GROUND, Attribute.SPECIAL, 10, 65, 85));
		moveMap.put("Psycho Cut", new Move("Psycho Cut", Type.PSYCHIC, Attribute.PHYSICAL, 20, 70, 100));
		moveMap.put("Zen Headbutt", new Move("Zen Headbutt", Type.PSYCHIC, Attribute.PHYSICAL, 15, 80, 90));
		moveMap.put("Mirror Shot", new Move("Mirror Shot", Type.STEEL, Attribute.SPECIAL, 10, 65, 85));
		moveMap.put("Flash Cannon", new Move("Flash Cannon", Type.STEEL, Attribute.SPECIAL, 10, 80, 100));
		moveMap.put("Rock Climb", new Move("Rock Climb", Type.NORMAL, Attribute.PHYSICAL, 20, 90, 85));
		moveMap.put("Defog", new Move("Defog", Type.FLYING, Attribute.STATUS, 15, -1, -1));
		moveMap.put("Trick Room", new Move("Trick Room", Type.PSYCHIC, Attribute.STATUS, 5, -1, -1));
		moveMap.put("Draco Meteor", new Move("Draco Meteor", Type.DRAGON, Attribute.SPECIAL, 5, 130, 90));
		moveMap.put("Discharge", new Move("Discharge", Type.ELECTRIC, Attribute.SPECIAL, 15, 80, 100));
		moveMap.put("Lava Plume", new Move("Lava Plume", Type.FIRE, Attribute.SPECIAL, 15, 80, 100));
		moveMap.put("Leaf Storm", new Move("Leaf Storm", Type.GRASS, Attribute.SPECIAL, 5, 130, 90));
		moveMap.put("Power Whip", new Move("Power Whip", Type.GRASS, Attribute.PHYSICAL, 10, 120, 85));
		moveMap.put("Rock Wrecker", new Move("Rock Wrecker", Type.ROCK, Attribute.PHYSICAL, 5, 150, 90));
		moveMap.put("Cross Poison", new Move("Cross Poison", Type.POISON, Attribute.PHYSICAL, 20, 70, 100));
		moveMap.put("Gunk Shot", new Move("Gunk Shot", Type.POISON, Attribute.PHYSICAL, 5, 120, 80));
		moveMap.put("Iron Head", new Move("Iron Head", Type.STEEL, Attribute.PHYSICAL, 15, 80, 100));
		moveMap.put("Magnet Bomb", new Move("Magnet Bomb", Type.STEEL, Attribute.PHYSICAL, 20, 60, -1));
		moveMap.put("Stone Edge", new Move("Stone Edge", Type.ROCK, Attribute.PHYSICAL, 5, 100, 80));
		moveMap.put("Captivate", new Move("Captivate", Type.NORMAL, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Stealth Rock", new Move("Stealth Rock", Type.ROCK, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Grass Knot", new Move("Grass Knot", Type.GRASS, Attribute.SPECIAL, 20, -1, 100));
		moveMap.put("Chatter", new Move("Chatter", Type.FLYING, Attribute.SPECIAL, 20, 65, 100));
		moveMap.put("Judgment", new Move("Judgment", Type.NORMAL, Attribute.SPECIAL, 10, 100, 100));
		moveMap.put("Bug Bite", new Move("Bug Bite", Type.BUG, Attribute.PHYSICAL, 20, 60, 100));
		moveMap.put("Charge Beam", new Move("Charge Beam", Type.ELECTRIC, Attribute.SPECIAL, 10, 50, 90));
		moveMap.put("Wood Hammer", new Move("Wood Hammer", Type.GRASS, Attribute.PHYSICAL, 15, 120, 100));
		moveMap.put("Aqua Jet", new Move("Aqua Jet", Type.WATER, Attribute.PHYSICAL, 20, 40, 100));
		moveMap.put("Attack Order", new Move("Attack Order", Type.BUG, Attribute.PHYSICAL, 15, 90, 100));
		moveMap.put("Defend Order", new Move("Defend Order", Type.BUG, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Heal Order", new Move("Heal Order", Type.BUG, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Head Smash", new Move("Head Smash", Type.ROCK, Attribute.PHYSICAL, 5, 150, 80));
		moveMap.put("Double Hit", new Move("Double Hit", Type.NORMAL, Attribute.PHYSICAL, 10, 35, 90));
		moveMap.put("Roar of Time", new Move("Roar of Time", Type.DRAGON, Attribute.SPECIAL, 5, 150, 90));
		moveMap.put("Spacial Rend", new Move("Spacial Rend", Type.DRAGON, Attribute.SPECIAL, 5, 100, 95));
		moveMap.put("Lunar Dance", new Move("Lunar Dance", Type.PSYCHIC, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Crush Grip", new Move("Crush Grip", Type.NORMAL, Attribute.PHYSICAL, 5, -1, 100));
		moveMap.put("Magma Storm", new Move("Magma Storm", Type.FIRE, Attribute.SPECIAL, 5, 100, 75));
		moveMap.put("Dark Void", new Move("Dark Void", Type.DARK, Attribute.STATUS, 10, -1, 80));
		moveMap.put("Seed Flare", new Move("Seed Flare", Type.GRASS, Attribute.SPECIAL, 5, 120, 85));
		moveMap.put("Ominous Wind", new Move("Ominous Wind", Type.GHOST, Attribute.SPECIAL, 5, 60, 100));
		moveMap.put("Shadow Force", new Move("Shadow Force", Type.GHOST, Attribute.PHYSICAL, 5, 120, 100));
		moveMap.put("Hone Claws", new Move("Hone Claws", Type.DARK, Attribute.STATUS, 15, -1, -1));
		moveMap.put("Wide Guard", new Move("Wide Guard", Type.ROCK, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Guard Split", new Move("Guard Split", Type.PSYCHIC, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Power Split", new Move("Power Split", Type.PSYCHIC, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Wonder Room", new Move("Wonder Room", Type.PSYCHIC, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Psyshock", new Move("Psyshock", Type.PSYCHIC, Attribute.SPECIAL, 10, 80, 100));
		moveMap.put("Venoshock", new Move("Venoshock", Type.POISON, Attribute.SPECIAL, 10, 65, 100));
		moveMap.put("Autotomize", new Move("Autotomize", Type.STEEL, Attribute.STATUS, 15, -1, -1));
		moveMap.put("Rage Powder", new Move("Rage Powder", Type.BUG, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Telekinesis", new Move("Telekinesis", Type.PSYCHIC, Attribute.STATUS, 15, -1, -1));
		moveMap.put("Magic Room", new Move("Magic Room", Type.PSYCHIC, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Smack Down", new Move("Smack Down", Type.ROCK, Attribute.PHYSICAL, 15, 50, 100));
		moveMap.put("Storm Throw", new Move("Storm Throw", Type.FIGHTING, Attribute.PHYSICAL, 10, 60, 100));
		moveMap.put("Flame Burst", new Move("Flame Burst", Type.FIRE, Attribute.SPECIAL, 15, 70, 100));
		moveMap.put("Sludge Wave", new Move("Sludge Wave", Type.POISON, Attribute.SPECIAL, 10, 95, 100));
		moveMap.put("Quiver Dance", new Move("Quiver Dance", Type.BUG, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Heavy Slam", new Move("Heavy Slam", Type.STEEL, Attribute.PHYSICAL, 10, -1, 100));
		moveMap.put("Synchronoise", new Move("Synchronoise", Type.PSYCHIC, Attribute.SPECIAL, 15, 120, 100));
		moveMap.put("Electro Ball", new Move("Electro Ball", Type.ELECTRIC, Attribute.SPECIAL, 10, -1, 100));
		moveMap.put("Soak", new Move("Soak", Type.WATER, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Flame Charge", new Move("Flame Charge", Type.FIRE, Attribute.PHYSICAL, 20, 50, 100));
		moveMap.put("Coil", new Move("Coil", Type.POISON, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Low Sweep", new Move("Low Sweep", Type.FIGHTING, Attribute.PHYSICAL, 20, 65, 100));
		moveMap.put("Acid Spray", new Move("Acid Spray", Type.POISON, Attribute.SPECIAL, 20, 40, 100));
		moveMap.put("Foul Play", new Move("Foul Play", Type.DARK, Attribute.PHYSICAL, 15, 95, 100));
		moveMap.put("Simple Beam", new Move("Simple Beam", Type.NORMAL, Attribute.STATUS, 15, -1, 100));
		moveMap.put("Entrainment", new Move("Entrainment", Type.NORMAL, Attribute.STATUS, 15, -1, 100));
		moveMap.put("After You", new Move("After You", Type.NORMAL, Attribute.STATUS, 15, -1, -1));
		moveMap.put("Round", new Move("Round", Type.NORMAL, Attribute.SPECIAL, 15, 60, 100));
		moveMap.put("Echoed Voice", new Move("Echoed Voice", Type.NORMAL, Attribute.SPECIAL, 15, 40, 100));
		moveMap.put("Chip Away", new Move("Chip Away", Type.NORMAL, Attribute.PHYSICAL, 20, 70, 100));
		moveMap.put("Clear Smog", new Move("Clear Smog", Type.POISON, Attribute.SPECIAL, 15, 50, -1));
		moveMap.put("Stored Power", new Move("Stored Power", Type.PSYCHIC, Attribute.SPECIAL, 10, 20, 100));
		moveMap.put("Quick Guard", new Move("Quick Guard", Type.FIGHTING, Attribute.STATUS, 15, -1, -1));
		moveMap.put("Ally Switch", new Move("Ally Switch", Type.PSYCHIC, Attribute.STATUS, 15, -1, -1));
		moveMap.put("Scald", new Move("Scald", Type.WATER, Attribute.SPECIAL, 15, 80, 100));
		moveMap.put("Shell Smash", new Move("Shell Smash", Type.NORMAL, Attribute.STATUS, 15, -1, -1));
		moveMap.put("Heal Pulse", new Move("Heal Pulse", Type.PSYCHIC, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Hex", new Move("Hex", Type.GHOST, Attribute.SPECIAL, 10, 65, 100));
		moveMap.put("Sky Drop", new Move("Sky Drop", Type.FLYING, Attribute.PHYSICAL, 10, 60, 100));
		moveMap.put("Shift Gear", new Move("Shift Gear", Type.STEEL, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Circle Throw", new Move("Circle Throw", Type.FIGHTING, Attribute.PHYSICAL, 10, 60, 90));
		moveMap.put("Incinerate", new Move("Incinerate", Type.FIRE, Attribute.SPECIAL, 15, 60, 100));
		moveMap.put("Quash", new Move("Quash", Type.DARK, Attribute.STATUS, 15, -1, 100));
		moveMap.put("Acrobatics", new Move("Acrobatics", Type.FLYING, Attribute.PHYSICAL, 15, 55, 100));
		moveMap.put("Reflect Type", new Move("Reflect Type", Type.NORMAL, Attribute.STATUS, 15, -1, -1));
		moveMap.put("Retaliate", new Move("Retaliate", Type.NORMAL, Attribute.PHYSICAL, 5, 70, 100));
		moveMap.put("Final Gambit", new Move("Final Gambit", Type.FIGHTING, Attribute.SPECIAL, 5, -1, 100));
		moveMap.put("Bestow", new Move("Bestow", Type.NORMAL, Attribute.STATUS, 15, -1, -1));
		moveMap.put("Inferno", new Move("Inferno", Type.FIRE, Attribute.SPECIAL, 5, 100, 50));
		moveMap.put("Water Pledge", new Move("Water Pledge", Type.WATER, Attribute.SPECIAL, 10, 80, 100));
		moveMap.put("Fire Pledge", new Move("Fire Pledge", Type.FIRE, Attribute.SPECIAL, 10, 80, 100));
		moveMap.put("Grass Pledge", new Move("Grass Pledge", Type.GRASS, Attribute.SPECIAL, 10, 80, 100));
		moveMap.put("Volt Switch", new Move("Volt Switch", Type.ELECTRIC, Attribute.SPECIAL, 20, 70, 100));
		moveMap.put("Struggle Bug", new Move("Struggle Bug", Type.BUG, Attribute.SPECIAL, 20, 50, 100));
		moveMap.put("Bulldoze", new Move("Bulldoze", Type.GROUND, Attribute.PHYSICAL, 20, 60, 100));
		moveMap.put("Frost Breath", new Move("Frost Breath", Type.ICE, Attribute.SPECIAL, 10, 60, 90));
		moveMap.put("Dragon Tail", new Move("Dragon Tail", Type.DRAGON, Attribute.PHYSICAL, 10, 60, 90));
		moveMap.put("Work Up", new Move("Work Up", Type.NORMAL, Attribute.STATUS, 30, -1, -1));
		moveMap.put("Electroweb", new Move("Electroweb", Type.ELECTRIC, Attribute.SPECIAL, 15, 55, 95));
		moveMap.put("Wild Charge", new Move("Wild Charge", Type.ELECTRIC, Attribute.PHYSICAL, 15, 90, 100));
		moveMap.put("Drill Run", new Move("Drill Run", Type.GROUND, Attribute.PHYSICAL, 10, 80, 95));
		moveMap.put("Dual Chop", new Move("Dual Chop", Type.DRAGON, Attribute.PHYSICAL, 15, 40, 90));
		moveMap.put("Heart Stamp", new Move("Heart Stamp", Type.PSYCHIC, Attribute.PHYSICAL, 25, 60, 100));
		moveMap.put("Horn Leech", new Move("Horn Leech", Type.GRASS, Attribute.PHYSICAL, 10, 75, 100));
		moveMap.put("Sacred Sword", new Move("Sacred Sword", Type.FIGHTING, Attribute.PHYSICAL, 15, 90, 100));
		moveMap.put("Razor Shell", new Move("Razor Shell", Type.WATER, Attribute.PHYSICAL, 10, 75, 95));
		moveMap.put("Heat Crash", new Move("Heat Crash", Type.FIRE, Attribute.PHYSICAL, 10, -1, 100));
		moveMap.put("Leaf Tornado", new Move("Leaf Tornado", Type.GRASS, Attribute.SPECIAL, 10, 65, 90));
		moveMap.put("Steamroller", new Move("Steamroller", Type.BUG, Attribute.PHYSICAL, 20, 65, 100));
		moveMap.put("Cotton Guard", new Move("Cotton Guard", Type.GRASS, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Night Daze", new Move("Night Daze", Type.DARK, Attribute.SPECIAL, 10, 85, 95));
		moveMap.put("Psystrike", new Move("Psystrike", Type.PSYCHIC, Attribute.SPECIAL, 10, 100, 100));
		moveMap.put("Tail Slap", new Move("Tail Slap", Type.NORMAL, Attribute.PHYSICAL, 10, 25, 85));
		moveMap.put("Hurricane", new Move("Hurricane", Type.FLYING, Attribute.SPECIAL, 10, 110, 70));
		moveMap.put("Head Charge", new Move("Head Charge", Type.NORMAL, Attribute.PHYSICAL, 15, 120, 100));
		moveMap.put("Gear Grind", new Move("Gear Grind", Type.STEEL, Attribute.PHYSICAL, 15, 50, 85));
		moveMap.put("Searing Shot", new Move("Searing Shot", Type.FIRE, Attribute.SPECIAL, 5, 100, 100));
		moveMap.put("Techno Blast", new Move("Techno Blast", Type.NORMAL, Attribute.SPECIAL, 5, 120, 100));
		moveMap.put("Relic Song", new Move("Relic Song", Type.NORMAL, Attribute.SPECIAL, 10, 75, 100));
		moveMap.put("Secret Sword", new Move("Secret Sword", Type.FIGHTING, Attribute.SPECIAL, 10, 85, 100));
		moveMap.put("Glaciate", new Move("Glaciate", Type.ICE, Attribute.SPECIAL, 10, 65, 95));
		moveMap.put("Bolt Strike", new Move("Bolt Strike", Type.ELECTRIC, Attribute.PHYSICAL, 5, 130, 85));
		moveMap.put("Blue Flare", new Move("Blue Flare", Type.FIRE, Attribute.SPECIAL, 5, 130, 85));
		moveMap.put("Fiery Dance", new Move("Fiery Dance", Type.FIRE, Attribute.SPECIAL, 10, 80, 100));
		moveMap.put("Freeze Shock", new Move("Freeze Shock", Type.ICE, Attribute.PHYSICAL, 5, 140, 90));
		moveMap.put("Ice Burn", new Move("Ice Burn", Type.ICE, Attribute.SPECIAL, 5, 140, 90));
		moveMap.put("Snarl", new Move("Snarl", Type.DARK, Attribute.SPECIAL, 15, 55, 95));
		moveMap.put("Icicle Crash", new Move("Icicle Crash", Type.ICE, Attribute.PHYSICAL, 10, 85, 90));
		moveMap.put("V-create", new Move("V-create", Type.FIRE, Attribute.PHYSICAL, 5, 180, 95));
		moveMap.put("Fusion Flare", new Move("Fusion Flare", Type.FIRE, Attribute.SPECIAL, 5, 100, 100));
		moveMap.put("Fusion Bolt", new Move("Fusion Bolt", Type.ELECTRIC, Attribute.PHYSICAL, 5, 100, 100));
		moveMap.put("Flying Press", new Move("Flying Press", Type.FIGHTING, Attribute.PHYSICAL, 10, 80, 95));
		moveMap.put("Mat Block", new Move("Mat Block", Type.FIGHTING, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Belch", new Move("Belch", Type.POISON, Attribute.SPECIAL, 10, 120, 90));
		moveMap.put("Rototiller", new Move("Rototiller", Type.GROUND, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Sticky Web", new Move("Sticky Web", Type.BUG, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Fell Stinger", new Move("Fell Stinger", Type.BUG, Attribute.PHYSICAL, 25, 30, 100));
		moveMap.put("Phantom Force", new Move("Phantom Force", Type.GHOST, Attribute.PHYSICAL, 10, 90, 100));
		moveMap.put("Trick-or-Treat", new Move("Trick-or-Treat", Type.GHOST, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Noble Roar", new Move("Noble Roar", Type.NORMAL, Attribute.STATUS, 30, -1, 100));
		moveMap.put("Ion Deluge", new Move("Ion Deluge", Type.ELECTRIC, Attribute.STATUS, 25, -1, -1));
		moveMap.put("Parabolic Charge", new Move("Parabolic Charge", Type.ELECTRIC, Attribute.SPECIAL, 20, 50, 100));
		moveMap.put("Forest's Curse", new Move("Forest's Curse", Type.GRASS, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Petal Blizzard", new Move("Petal Blizzard", Type.GRASS, Attribute.PHYSICAL, 15, 90, 100));
		moveMap.put("Freeze-Dry", new Move("Freeze-Dry", Type.ICE, Attribute.SPECIAL, 20, 70, 100));
		moveMap.put("Disarming Voice", new Move("Disarming Voice", Type.FAIRY, Attribute.SPECIAL, 15, 40, -1));
		moveMap.put("Parting Shot", new Move("Parting Shot", Type.DARK, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Topsy-Turvy", new Move("Topsy-Turvy", Type.DARK, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Draining Kiss", new Move("Draining Kiss", Type.FAIRY, Attribute.SPECIAL, 10, 50, 100));
		moveMap.put("Crafty Shield", new Move("Crafty Shield", Type.FAIRY, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Flower Shield", new Move("Flower Shield", Type.FAIRY, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Grassy Terrain", new Move("Grassy Terrain", Type.GRASS, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Misty Terrain", new Move("Misty Terrain", Type.FAIRY, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Electrify", new Move("Electrify", Type.ELECTRIC, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Play Rough", new Move("Play Rough", Type.FAIRY, Attribute.PHYSICAL, 10, 90, 90));
		moveMap.put("Fairy Wind", new Move("Fairy Wind", Type.FAIRY, Attribute.SPECIAL, 30, 40, -1));
		moveMap.put("Moonblast", new Move("Moonblast", Type.FAIRY, Attribute.SPECIAL, 15, 95, 100));
		moveMap.put("Boomburst", new Move("Boomburst", Type.NORMAL, Attribute.SPECIAL, 10, 140, 100));
		moveMap.put("Fairy Lock", new Move("Fairy Lock", Type.FAIRY, Attribute.STATUS, 10, -1, -1));
		moveMap.put("King's Shield", new Move("King's Shield", Type.STEEL, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Play Nice", new Move("Play Nice", Type.NORMAL, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Confide", new Move("Confide", Type.NORMAL, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Diamond Storm", new Move("Diamond Storm", Type.ROCK, Attribute.PHYSICAL, 5, 100, 95));
		moveMap.put("Steam Eruption", new Move("Steam Eruption", Type.WATER, Attribute.SPECIAL, 5, 110, 95));
		moveMap.put("Hyperspace Hole", new Move("Hyperspace Hole", Type.PSYCHIC, Attribute.SPECIAL, 5, 80, -1));
		moveMap.put("Water Shuriken", new Move("Water Shuriken", Type.WATER, Attribute.PHYSICAL, 20, 15, 100));
		moveMap.put("Mystical Fire", new Move("Mystical Fire", Type.FIRE, Attribute.SPECIAL, 10, 65, 100));
		moveMap.put("Spiky Shield", new Move("Spiky Shield", Type.GRASS, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Aromatic Mist", new Move("Aromatic Mist", Type.FAIRY, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Eerie Impulse", new Move("Eerie Impulse", Type.ELECTRIC, Attribute.STATUS, 15, -1, 100));
		moveMap.put("Venom Drench", new Move("Venom Drench", Type.POISON, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Powder", new Move("Powder", Type.BUG, Attribute.STATUS, 20, -1, 100));
		moveMap.put("Geomancy", new Move("Geomancy", Type.FAIRY, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Magnetic Flux", new Move("Magnetic Flux", Type.ELECTRIC, Attribute.STATUS, 20, -1, -1));
		moveMap.put("Happy Hour", new Move("Happy Hour", Type.NORMAL, Attribute.STATUS, 30, -1, -1));
		moveMap.put("Electric Terrain", new Move("Electric Terrain", Type.ELECTRIC, Attribute.STATUS, 10, -1, -1));
		moveMap.put("Dazzling Gleam", new Move("Dazzling Gleam", Type.FAIRY, Attribute.SPECIAL, 10, 80, 100));
		moveMap.put("Celebrate", new Move("Celebrate", Type.NORMAL, Attribute.STATUS, 40, -1, -1));
		moveMap.put("Hold Hands", new Move("Hold Hands", Type.NORMAL, Attribute.STATUS, 40, -1, -1));
		moveMap.put("Baby-Doll Eyes", new Move("Baby-Doll Eyes", Type.FAIRY, Attribute.STATUS, 30, -1, 100));
		moveMap.put("Nuzzle", new Move("Nuzzle", Type.ELECTRIC, Attribute.PHYSICAL, 20, 20, 100));
		moveMap.put("Hold Back", new Move("Hold Back", Type.NORMAL, Attribute.PHYSICAL, 40, 40, 100));
		moveMap.put("Infestation", new Move("Infestation", Type.BUG, Attribute.SPECIAL, 20, 20, 100));
		moveMap.put("Power-Up Punch", new Move("Power-Up Punch", Type.FIGHTING, Attribute.PHYSICAL, 20, 40, 100));
		moveMap.put("Oblivion Wing", new Move("Oblivion Wing", Type.FLYING, Attribute.SPECIAL, 10, 80, 100));
		moveMap.put("Thousand Arrows", new Move("Thousand Arrows", Type.GROUND, Attribute.PHYSICAL, 10, 90, 100));
		moveMap.put("Thousand Waves", new Move("Thousand Waves", Type.GROUND, Attribute.PHYSICAL, 10, 90, 100));
		moveMap.put("Land's Wrath", new Move("Land's Wrath", Type.GROUND, Attribute.PHYSICAL, 10, 90, 100));
		moveMap.put("Light of Ruin", new Move("Light of Ruin", Type.FAIRY, Attribute.SPECIAL, 5, 140, 90));
		moveMap.put("Origin Pulse", new Move("Origin Pulse", Type.WATER, Attribute.SPECIAL, 10, 110, 85));
		moveMap.put("Precipice Blades", new Move("Precipice Blades", Type.GROUND, Attribute.PHYSICAL, 10, 120, 85));
		moveMap.put("Dragon Ascent", new Move("Dragon Ascent", Type.FLYING, Attribute.PHYSICAL, 5, 120, 100));
		moveMap.put("Hyperspace Fury", new Move("Hyperspace Fury", Type.DARK, Attribute.PHYSICAL, 5, 100, -1));
	}
}